### ISSUE TITLE
Chef Automate EAS Applications Documentation

### ISSUE THREAD

**Issue by kagarmoe** [chef/automate#1673] opened 2019-09-19 21:37 UTC
The Chef Automate EAS Applications Beta Documentation is getting ready for GA.

- [x] Convert from GDoc to Markdown
- [x] Test it out
- [x] Edits and reviews

**Comment by vjeffrey** [comment] 2019-10-21 03:48
i believe this is a duplicate of https://github.com/chef/automate/issues/1651 ?

**Comment by susanev** [comment] 2020-08-28 14:40
this work has been completed

**Closed by susanev** 2020-08-28 14:40 UTC
Labels: documentation
