### ISSUE TITLE
Pressing <enter> causes browser console error

### ISSUE THREAD

**Issue by msorens** [chef/automate#1592] opened 2019-09-12 20:58 UTC
## Describe the bug

Pressing `<enter>` in some form field inputs causes a browser console error.
Spot checking revealed this is a widespread issue--this is not a complete list:

- create team
- edit team
- create token
- policy "Add Member Expression"
- create integration
- add credential

Other than the reported console error (which you will see only with the dev console opened) there seems to be no deleterious efffect.

## To Reproduce
Login to automate in the browser
Open the dev tools console.
Go to, e.g. Settings >> Teams >> Create Team
Press `<enter>` in the name field.

## Expected behavior
No error--key should just be ignored.

## Screenshots

![image](https://user-images.githubusercontent.com/6817500/64819229-a435a080-d562-11e9-89b7-cb76931f5c02.png)

## Versions (please complete the following information):
- OS: macOS
- Browser: occurs in Chrome 76; does not occur in Firefox 69 or Safari 12.
- Automate Build Number: 20190912201508

## Technical Note
This seems to occur on both `<input>` elements with `chefInput` and `<chef-input>` elements as well.

**Comment by vinay033** [comment] 2019-11-04 08:59
Hi @msorens and @susanev 
currently, we are using a Linux machine for development, so we are not able to reproduce this issue.

**Comment by msorens** [comment] 2019-11-04 17:06
@vinay033 So just to be clear: are you saying you have tried specifically with Chrome on your machine and the error does not occur?

**Comment by vinay033** [comment] 2019-11-06 07:08
@msorens tried with Chrome as well as Firefox but not able to reproduce issue. Version specifications as given bellow 
OS: Ubuntu 18.04.1 LTS
Browser: does not occur in Chrome 76 or Firefox 70.
Automate Version: 2
Automate Build Number: 20191105204247

**Comment by susanev** [comment] 2019-11-13 22:29
im not able to repro this on..
osx 10.13.6
chrome Version 78.0.3904.87

**Comment by susanev** [comment] 2019-11-13 22:31
oh nevermind! found it. tab to the input, press enter.

**Comment by susanev** [comment] 2020-03-06 21:54
this work has been deprioritized, so closing.

**Closed by susanev** 2020-03-06 21:54 UTC
Labels: automate-ui, bug 🐛, ui
