### ISSUE TITLE
when a compliance or client run node's role, chef tag, or any array field for projects is null the project update fails

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1494] opened 2019-09-06 21:39 UTC
## User Story

As an Automate User, I will use this work when I want to apply projects to ingested resources.

During a demo, we ran into the following bug where Elasticsearch got into a bad state when a project update attempted to update a scan job's projects. The projects field does not yet exist on scan jobs. After hitting this error once, project update no longer works for any ingested resource.

## Demo Script / Repro Steps
1. Upgrade to beta2.1 and load data
```
chef-automate iam upgrade-to-v2 --beta2.1
chef_load_nodes 20
chef_load_compliance_scans -N10 -M100 -T10 -D10
chef_load_actions 20
```
2. Confirm project update works when there are no scan jobs 

- log in to the UI as `admin`
- go to infrastructure > client runs
- identify some environments in the table view
- create a new project
- add a node ingest rule for the environment you identified
- run `sl | grep elastic` in your studio
- update projects
- you'll see the following elasticsearch logs in the server logs:
```
[2019-09-06T19:47:58+00:00] automate-elasticsearch.default(O): [2019-09-06T19:47:58,849][WARN ][o.e.m.j.JvmGcMonitorService] [fWalQHA] [gc][2239] overhead, spent [1.1s] collecting in the last [1.7s]
[2019-09-06T19:48:00+00:00] automate-elasticsearch.default(O): [2019-09-06T19:48:00,099][INFO ][o.e.t.LoggingTaskListener] 74999 finished with response BulkByScrollResponse[took=3.5s,timed_out=false,sliceId=null,updated=1030,created=0,deleted=0,batches=2,versionConflicts=0,noops=0,retries=0,throttledUntil=0s,bulk_failures=[],search_failures=[]]
[2019-09-06T19:48:24+00:00] automate-elasticsearch.default(O): [2019-09-06T19:48:24,622][INFO ][o.e.t.LoggingTaskListener] 74977 finished with response BulkByScrollResponse[took=28s,timed_out=false,sliceId=null,updated=1030,created=0,deleted=0,batches=2,versionConflicts=0,noops=0,retries=0,throttledUntil=0s,bulk_failures=[],search_failures=[]]
```
- go back to client runs
- filter your projects view and you should see only nodes for that project you created

3. Add a scan job
```
send_inspec_example
```

4. During the project update operation, elasticsearch fails to apply a project to the scan job
- create a new project called `tiny`
- add a Node ingest rule with the condition 
```
attribute: Chef Organization 
operator: equals 
value: tiny
```
- run `sl | grep elastic` in your studio
- open the network tab in your dev tools and filter for `apply-rules` calls
- update projects
- you will see no error message in the UI and no failed `apply-rules` responses in the network tab, but you should see the following error in the server logs:
```
[2019-09-06T19:55:33+00:00] automate-elasticsearch.default(O): [2019-09-06T19:55:33,449][WARN ][o.e.t.LoggingTaskListener] 78272 failed with exception
[2019-09-06T19:55:33+00:00] automate-elasticsearch.default(O): org.elasticsearch.script.ScriptException: runtime error
[2019-09-06T19:55:33+00:00] automate-elasticsearch.default(O): 	at org.elasticsearch.painless.PainlessScript.convertToScriptException(PainlessScript.java:101) ~[?:?]
[2019-09-06T19:55:33+00:00] automate-elasticsearch.default(O): 	at org.elasticsearch.painless.PainlessScript$Script.execute(ArrayList matchingProjects = new ArrayList();
[2019-09-06T19:55:33+00:00] automate-elasticsearch.default(O): 		for (def project : params.projects) {
[2019-09-06T19:55:33+00:00] automate-elasticsearch.default(O): 			for (def rule : project.rules) {
[2019-09-06T19:55:33+00:00] automate-elasticsearch.default(O): 				def match = rule.conditions.length != 0;
[2019-09-06T19:55:33+00:00] automate-elasticsearch.default(O): 				for (def condition : rule.conditions) {
[2019-09-06T19:55:33+00:00] automate-elasticsearch.default(O): 					if (condition.chefServers.length > 0) {
[2019-09-06T19:55:33+00:00] automate-elasticsearch.default(O):  ...:2581) ~[?:?]
[2019-09-06T19:55:33+00:00] automate-elasticsearch.default(O): 	at org.elasticsearch.painless.ScriptImpl.run(ScriptImpl.java:105) ~[?:?]
```

5. Attempting another project update results in the same error
- go back to that infra node project you made in the 2nd step
- change the rule (change the attribute, add a new value, etc)
- run `sl | grep elastic` in your studio
- update projects
- the same elasticsearch error as above should appear

## Definition of Done
- project update reports elasticsearch failures, which get bubbled up to the UI as an error message after clicking `Update Projects`
- project update succeeds even when resources that haven't implemented projects (like scan jobs) exist in the system

**Comment by lancewf** [comment] 2019-10-08 22:21
I ran through the steps and was not able to reproduce the error. I am going to update the code to cause an error and see what happens.

**Comment by lancewf** [comment] 2019-10-08 22:51
When simulating an error from the ingest-service, compliance-service and killing elasticsearch during the update a failure message was properly returned.

When killing elasticsearch I got the below error from the apply-rules request. 
`{"state":"not_running","estimated_time_complete":"0001-01-01T00:00:00Z","percentage_complete":1,"failed":true,"failure_message":"; ingest: task lost before reporting its status; compliance: task lost before reporting its status","cancelled":false}`

**Comment by lancewf** [comment] 2019-10-08 22:52
@bcmdarroch would you have time to try to reproduce the error again? I am not having any luck.

**Comment by bcmdarroch** [comment] 2019-10-15 00:50
Unable to repro the error, so this was either fixed or caused by some temporary dev environment issues

**Comment by bcmdarroch** [comment] 2019-10-25 22:54
we have been able to repro this error on the environment: https://a2-iamv2p1-local-inplace-upgrade-acceptance.cd.chef.co

unable to repro on these environments:
- local
- https://a2-local-inplace-upgrade-dev.cd.chef.co
- https://a2-local-fresh-install-dev.cd.chef.co
- https://a2-local-fresh-install-acceptance.cd.chef.co
- https://a2-local-inplace-upgrade-acceptance.cd.chef.co

**Comment by vjeffrey** [comment] 2019-10-28 17:08
investigation issue - small tshirt size

**Comment by lancewf** [comment] 2019-10-28 21:03
Two problems here. The first problem is when a compliance report's role, chef tag, or any array field used for project tags is null the project update fails. The second problem is that when the project update fails an error was not returned to the project update manager. 

I assume this is not a problem for only the compliance-service. This should be fixed for client runs also.

**Closed** 2019-11-01 20:55 UTC
Labels: auth-team, bug 🐛, iamv2
