### ISSUE TITLE
Node client run history pagination selector disappears when accessing beyond end of multi-day history

### ISSUE THREAD

**Issue by jraidan** [chef/automate#4366] opened 2020-09-22 17:20 UTC
## Describe the bug
From customer:
"When accessing multi-day node client run history, it seems when the selection goes past what is in the database, the pagination selector at the bottom disappears. The only fix is to refresh the page and then go back to the end.  This is annoying when we want to see the “beginning of history” on our recently Provisioned servers from a week or two ago.. We select 1 month then go through 20 pages then find the end and can’t change the selection. Then refresh and go one page at a time not to go past the last page."

## To Reproduce
- Navigate to the client run for a node, uptime 15 days for our repro case
- Click "Run History" blue button on right top
- Use nav buttons at bottom to get to last available page (page 8 for us), the dropdown selection is at 24 hrs (Default?)
- Select an older selection from drop-down, eg "Last month", Click "Apply"
- Use nav buttons at bottom to get to the last available page (page 12 now)
- The selection window closes
- Re-open the select window with "Run History" button
- The bottom pagination selector is now gone until you reload/refresh the page.

## Expected behavior
The "Run History" bottom page nav shouldn't poof.

## Versions (please complete the following information):
- Browser: Chrome
- Automate Build Number: 20200728181447

**Comment by stevenoneill** [comment] 2020-09-22 17:34
I experienced this one just earlier today.

**Comment by susanev** [comment] 2020-09-22 21:09
thanks for reporting this @jraidan!! weve pulled it into the workload for our ui team and they should be able to address it soon.

**Comment by SEAjamieD** [comment] 2020-11-13 23:48
I thought I had a fix for this today, but ultimately realized the issue is deeper in with the math involved for the optional `maxPageItems` property.  We haven't noticed it before because its the only place in the codebase were we use this property.  I'll also double check that this NOT being used isn't causing other pagination components to pop out of their containers.

**Closed** 2020-11-18 17:04 UTC
Labels: automate-ui, bug 🐛, customer-reported, good first issue, ui
