### ISSUE TITLE
Quantum State: Both getting and not getting a resource simultaneously

### ISSUE THREAD

**Issue by msorens** [chef/automate#1825] opened 2019-10-09 03:40 UTC
## User Story

As an Automate User, I want to avoid quantum state conditions. Notice in the image that the error clearly states we cannot access the policy... while it is displaying said policy.

![image.png](https://images.zenhubusercontent.com/5d07f7b39943fc312156c891/0c79f17c-a94a-431a-b355-110f4e53218a)

This particular policy is on this acceptance box:
https://a2-local-inplace-upgrade-acceptance.cd.chef.co/settings/policies/cb90417f-6f6a-4b7d-bb3f-b4c816dfc1ac

Here's the content:
```
{
  "name": "cb90417f-6f6a-4b7d-bb3f-b4c816dfc1ac (custom)",
  "id": "cb90417f-6f6a-4b7d-bb3f-b4c816dfc1ac",
  "type": "CUSTOM",
  "statements": [
    {
      "effect": "ALLOW",
      "actions": [
        "*"
      ],
      "resources": [
        "iam:policies"
      ],
      "projects": [
        "*"
      ]
    }
  ],
  "projects": []
}
```
The error message is valid, because we are only giving permission for `iam:policies`, not `iam:policies:*`. So why does the policy get displayed? Because it is in the ngrx/store (from ListPolicies), and that is used on the policy details page--_at the same time we make a request to fetch the policy_.

If we are going to use the policy already in the ngrx/store, no need to do another fetch for the same thing. But should we do that? It does an end-run around permissioning as this use case vividly demonstrates: based on granted permissions, the user should not be able to see the details. Which implies the correct solution is to never use what was fetched with ListPolicies to display policy details.

Note that while this case discusses a policy that started in V1 (because there's a resource), then migrated to v2, I do not believe that is significant. The same thing should manifest strictly on V2.

## Definition of Done

Depends on discussion of above.

## Demo Script / Repro Steps

Create a V1 policy containing this:
```
jq -n '{action: "*", resource: "auth:policies", subjects: ["user:local:coolbeans"]}'
```
Migrate to v2.
Login as coolbeans, then visit the Policies List page, and select a policy to see its details.

**Comment by bcmdarroch** [comment] 2019-10-15 15:19
I'm curious if there's a use case for allowing a user to see the list of policies, but not individual policies. Sure, in the UI, they have a more limited view of policies if they just have list permission. But if they use CLI to curl `GET /policies` they can see all the policy details that they would see on the details page. Should Get and List use the same permission?

**Comment by bcmdarroch** [comment] 2019-10-15 15:29
all the things

**Comment by susanev** [comment] 2019-10-15 15:35
prefer, policies you do not have access on do not display a link to navigate there.

**Comment by susanev** [comment] 2019-10-20 18:37
in backlog grooming, we discussed closing this issue and @msorens opening a new issue to fix the root cause

**Comment by bcmdarroch** [comment] 2019-11-13 21:28
resolved by https://github.com/chef/automate/pull/2130 & https://github.com/chef/automate/pull/2158

**Closed by bcmdarroch** 2019-11-13 21:28 UTC
Labels: auth-team, automate-auth, automate-ui, bug 🐛, ui
