### ISSUE TITLE
Date & Time format - need setting to change

### ISSUE THREAD

**Issue by vivekvardwaz** [chef/automate#4606] opened 2021-01-21 05:53 UTC
The A2 server GUI is showing date and time in US format (e.g. 09/25/2018 2.15PM). Where can we find the setting to change it to ISO8601 format (2018-09-25 14:15)?

https://chef.aha.io/epics/A2-E-152?active_tab=related

**Comment by AnkurMundhra** [comment] 2021-02-18 07:28
Duplicate of #4745.

**Closed** 2021-02-18 07:28 UTC
Labels: ui, ux
