### ISSUE TITLE
Client Runs for Environments Containing Hyphen Characters Are Not Returned in Automate's Search Function

### ISSUE THREAD

**Issue by cdbeard2016** [chef/automate#221] opened 2019-05-01 10:54 UTC
# User Story

As an Operations Engineer, I want to search for client runs by any valid environment name.

# Demo Script / Repro Steps

Versions:
Chef workstation: 0.2.48
Chef Automate: 20190422213145
Chef Manage: 2.5.15

In Chef Manage you can have a valid environment name which contains hyphen characters.

Add two environments 
```
knife environment create Test-Environment
knife environment create Test_Environment
```

Take a test node and add it to one of the new environments, run the chef-client for this node manually to create a run for chef automate to find, repeat for the second environment.
Then in automate go to Client Runs and create a search for Environment and “Test”, you will see that only one environment is found. You can also search for the node by name and see that only one chef-run is recorded which is the non-hyphenated one.

![image](https://user-images.githubusercontent.com/23032545/57014257-45046e80-6c07-11e9-9db1-0a78a1957f08.png)

As a workaround you can have an internal naming convention of no hyphens. It would be nice for the search in automate to pick up all valid environment names though!

Many thanks,

Chris

**Comment by vjeffrey** [comment] 2019-05-06 02:13
hi @cdbeard2016, thanks for opening the issue! 
This is indeed an issue we're aware of; thank you for the details and screenshots!

I'll get this added to our board. We'll try to get to it soon, but it will likely be a few weeks as we've got some in progress work that needs to be wrapped up.

**Comment by lancewf** [comment] 2019-05-20 16:57
Hello Chris @cdbeard2016, I was not able to reproduce the problem where environments having hyphen characters are not showing up in the Automate search function. As shown in the below image I created two nodes with the environments of "Test-Environment" and "Test_Environment". Then in Automate's Client Runs page's search bar typed "test" and was displayed both environments. 

You could be seeing only one of the environments if you are using the same node in your demo script. The way that the environment values are collected is from the latest run on each node. So, if you set the node to have the environment "Test-Environment" then ran chef-client on that node. Then switch that same node to have the environment "Test_Environment" and reran chef-client, it is correct that you should only see the second run's environment of "Test_Environment".

**Comment by vjeffrey** [comment] 2019-05-20 20:14
@cdbeard2016 i'm going to close this issue for now as we have not been able to reproduce, but please do open it back up again with further details if you find it to be a continuing issuee

**Closed** 2019-05-20 20:15 UTC
Labels: bug, client runs
