### ISSUE TITLE
welcome modal comes back after dismissal

### ISSUE THREAD

**Issue by susanev** [chef/automate#1655] opened 2019-09-18 20:18 UTC
## Overview
Welcome modal comes back after dismissal.

## Repro steps
- sign in as admin
- navigate to settings > users
- create a new user
- navigate to teams > admin team, add ur new user to the admin team
- sign out as admin and in as ur new user
- observe the welcome modal
- dismiss the welcome modal
- refresh your browser again
- see the welcome modal again

## Desired Behaviour
If you dismiss the welcome modal it shouldn't come back.

## Screenshots
![](https://user-images.githubusercontent.com/5489125/65183135-ae9ae300-da17-11e9-9793-fb694864102f.png)

**Comment by blakestier** [comment] 2019-09-18 23:22
Modal also reappears whenever a new license is applied.

Repro steps:
- log in as admin
- run `chef-automate dev psql chef_license_control_service -- -c "UPDATE licenses SET active=NULL"` from studio to remove license
- request a license (see welcome modal)
- remove license again
- apply valid license
- see welcome modal again

Desired behavior:

- do not see welcome modal on application of license if user has previously used automate

**Comment by vinay033** [comment] 2019-09-25 09:49
also if a user can navigate another tab like the default is infrastructure and I switch to compliance tab after that if I refresh the browser the same modal is reappears.

**Comment by SEAjamieD** [comment] 2019-10-07 21:37
Will reach out to have someone else confirm, but looking like this may have been fixed somewhere.  I'm dismissing the welcome modal, refreshing and it is not coming back.

**Comment by SEAjamieD** [comment] 2019-10-14 18:47
Note:  The current bug i'm seeing is that when the modal is dismissed the FIRST time, it will reappear.  After dismissal a SECOND time, the modal welcome modal remains suppressed.

**Comment by SEAjamieD** [comment] 2019-10-14 22:45
We have a specific function named `handleTriggerWelcome` that deals with the logic of when to show or suppress the welcome modal.  What's happening is the FIRST time a user logs in, we show the modal, but it's not actually complete.  The user does not have access to our Telemetry Opt-in.  After a page refresh, the modal then returns because the user hasn't made a Telemetry selection yet, this time the modal is showing with the Telemetry option - defaulted to `true`.

@susanev - Do we want to be showing the Telemetry question on the FIRST modal with a default selection, like what's already being shown in the SECOND modal?

FIRST MODAL
![FIRST MODAL.png](https://images.zenhubusercontent.com/5d7aa5d5d4249c0001cab607/dcf46b6a-2939-44d2-b93c-8ce5f74e4691)

SECOND MODAL
![SECOND MODAL.png](https://images.zenhubusercontent.com/5d7aa5d5d4249c0001cab607/7b04fc37-d83a-44ef-bbcf-9a14feb73e2c)

**Comment by susanev** [comment] 2019-10-14 22:50
@SEAjamieD whoa good find, yes we want to show the telemetry checkbox on the first showing of that modal, please. i think it needs to be unchecked by default as well, im pretty sure folks need to take an explicit action to allow that.

while we are here, do you mind fixing a few more things on this modal?

- change, the two links to display as our normal link style instead of that special styling and update the text to `Chef Automate Documentation` and `Learn Chef Rally`
- move the checkboxes above the button
- change button text to `Close`

**Comment by SEAjamieD** [comment] 2019-10-22 01:02
Personal Note: Telemetry Architecture Diagram: https://github.com/chef/automate/blob/master/dev-docs/diagrams/telemetry-service-ui.png

**Comment by susanev** [comment] 2020-03-15 23:14
this work has been deprioritized, so closing.

**Comment by SEAjamieD** [comment] 2020-06-17 21:58
I think we can actually close this now thanks to @jaym.  Can anyone else confirm?

**Comment by SEAjamieD** [comment] 2020-08-31 18:15
Closing - Confirmed this is now working as desired.

**Closed by SEAjamieD** 2020-08-31 18:15 UTC
Labels: automate-ui, bug 🐛, ui

**Comment by Shadae** [comment] 2020-09-01 18:30
Closed with https://github.com/chef/automate/pull/3725
