### ISSUE TITLE
Applications Service Detail Panel Updates when Filter Criteria Added

### ISSUE THREAD

**Issue by danielsdeleo** [chef/automate#1357] opened 2019-08-26 16:50 UTC
## User Story

As a <role: Automate User, Developer, etc>, I will use this work when I want to <use case>.

## Definition of Done

* Service cards only display services matching the filter criteria
* service counts by health status for chiclet filters are updated

**Comment by apriofrost** [comment] 2019-09-07 00:35
This seems to be a duplicate of #1296, shall we close this one?

**Closed** 2019-09-09 17:06 UTC
Labels: automate-ui, eas-team, ui
